//! The naming scheme is the only lookup key Phase 2 and Phase 3 have: there
//! is no second index from a domain object to its AXIAM resource or group. So
//! these names are a contract, and they are generated by one pure function
//! rather than formatted at each call site.
//!
//! The two rejection cases below are the ones with teeth. A dot in a slug
//! would split an MQTT topic segment, because the topic scheme maps path
//! separators onto dots; a colon would split a broker virtual host from a user
//! name, because RabbitMQ splits at the last colon. Neither fails at the point
//! the slug is accepted — both fail much later, in the broker, as a connection
//! that is refused for no visible reason.

use domo_bootstrap::naming::{self, Kind};

#[test]
fn resource_names_are_readable_and_type_prefixed() {
    assert_eq!(
        naming::resource_name(Kind::Site, "smoke-lakeside-park").unwrap(),
        "site:smoke-lakeside-park"
    );
    assert_eq!(
        naming::resource_name(Kind::Building, "smoke-north-tower").unwrap(),
        "building:smoke-north-tower"
    );
    assert_eq!(
        naming::resource_name(Kind::SiteCommon, "smoke-lakeside-park").unwrap(),
        "common:site:smoke-lakeside-park"
    );
    assert_eq!(
        naming::resource_name(Kind::BuildingCommon, "smoke-north-tower").unwrap(),
        "common:building:smoke-north-tower"
    );
    assert_eq!(
        naming::resource_name(Kind::Device, "apt-a1-light-1").unwrap(),
        "device:apt-a1-light-1"
    );
    assert_eq!(
        naming::resource_name(Kind::Portfolio, "").unwrap(),
        "portfolio",
        "a tenant has exactly one root and it needs no slug to be unique"
    );
}

#[test]
fn an_apartment_is_named_by_its_building_and_unit() {
    let slug = naming::apartment_slug("smoke-north-tower", "a1").unwrap();
    assert_eq!(slug, "smoke-north-tower-a1");
    assert_eq!(
        naming::resource_name(Kind::Apartment, &slug).unwrap(),
        "apartment:smoke-north-tower-a1"
    );
}

#[test]
fn group_names_follow_role_at_resource() {
    assert_eq!(
        naming::group_name("installer", Kind::Site, "smoke-lakeside-park").unwrap(),
        "installer@site:smoke-lakeside-park"
    );
    assert_eq!(
        naming::group_name("granted-operator", Kind::Device, "apt-a1-light-1").unwrap(),
        "granted-operator@device:apt-a1-light-1"
    );
    assert_eq!(
        naming::group_name("property-manager", Kind::Portfolio, "").unwrap(),
        "property-manager@portfolio"
    );
    assert_eq!(
        naming::group_name("common-operator", Kind::SiteCommon, "smoke-lakeside-park").unwrap(),
        "common-operator@common:site:smoke-lakeside-park"
    );
}

#[test]
fn the_same_name_under_two_parents_stays_two_distinct_resources() {
    // AXIAM has no uniqueness index on resource names (P-8), so two buildings
    // called `north` under different sites are legitimate and distinct. The
    // scheme must not collapse them, and a resolver must therefore search
    // under a parent rather than tenant-wide.
    let a = naming::resource_name(Kind::Apartment, &naming::apartment_slug("tower-a", "1").unwrap())
        .unwrap();
    let b = naming::resource_name(Kind::Apartment, &naming::apartment_slug("tower-b", "1").unwrap())
        .unwrap();
    assert_ne!(a, b, "unit 1 of two towers are different apartments");
}

#[test]
fn a_slug_containing_a_dot_is_rejected() {
    // The MQTT topic scheme maps path separators onto dots, so a dot inside a
    // slug would split what must stay one topic segment.
    let err = naming::validate_slug("lakeside.park").expect_err("a dot must be rejected");
    assert!(
        err.to_string().contains('.'),
        "the error shows the offending character: {err}"
    );
    assert!(naming::resource_name(Kind::Site, "lakeside.park").is_err());
}

#[test]
fn a_slug_containing_a_colon_is_rejected() {
    // RabbitMQ splits a virtual host from a user name at the LAST colon, so a
    // colon in a slug would repoint the split.
    let err = naming::validate_slug("lakeside:park").expect_err("a colon must be rejected");
    assert!(
        err.to_string().contains(':'),
        "the error shows the offending character: {err}"
    );
    assert!(naming::group_name("installer", Kind::Site, "lakeside:park").is_err());
}

#[test]
fn a_slug_must_be_lowercase_alphanumeric_and_hyphens() {
    for bad in ["", "Lakeside", "lakeside park", "lakeside_park", "lakeside/park"] {
        assert!(
            naming::validate_slug(bad).is_err(),
            "slug {bad:?} must be rejected"
        );
    }
    for good in ["lakeside", "smoke-lakeside-park", "apt-a1-light-1", "a1"] {
        assert!(
            naming::validate_slug(good).is_ok(),
            "slug {good:?} must be accepted"
        );
    }
}

#[test]
fn structural_groups_match_d21_per_resource_type() {
    assert_eq!(
        naming::structural_groups_for(Kind::Portfolio),
        vec!["property-manager"]
    );
    assert_eq!(
        naming::structural_groups_for(Kind::Site),
        vec!["installer", "concierge"]
    );
    assert_eq!(
        naming::structural_groups_for(Kind::SiteCommon),
        vec!["common-operator", "common-device-manager"]
    );
    assert_eq!(
        naming::structural_groups_for(Kind::BuildingCommon),
        vec!["common-operator", "common-device-manager"]
    );
    assert_eq!(naming::structural_groups_for(Kind::Apartment), vec!["resident"]);
}

#[test]
fn a_device_gets_no_eager_group() {
    // A device's `granted-operator` group is created on the first grant, in
    // Phase 2, and deleted on revoke — creating it eagerly would leave an
    // empty group on every device, which reads as a grant that is not there.
    assert!(naming::structural_groups_for(Kind::Device).is_empty());
}

#[test]
fn a_building_gets_no_eager_group() {
    // A building's own devices live under its `common:building` node, and an
    // installer reaches its buildings through the site-level binding, which
    // cascades. D-21 lists no group at building level.
    assert!(naming::structural_groups_for(Kind::Building).is_empty());
}

#[test]
fn every_resource_kind_has_an_axiam_resource_type() {
    assert_eq!(naming::resource_type(Kind::Portfolio), "portfolio");
    assert_eq!(naming::resource_type(Kind::Site), "site");
    assert_eq!(naming::resource_type(Kind::SiteCommon), "common");
    assert_eq!(naming::resource_type(Kind::BuildingCommon), "common");
    assert_eq!(naming::resource_type(Kind::Building), "building");
    assert_eq!(naming::resource_type(Kind::Apartment), "apartment");
    assert_eq!(naming::resource_type(Kind::Device), "device");
}

#[test]
fn the_group_scheme_agrees_with_the_catalog_templates() {
    // `naming.rs` and `authz/catalog.toml` must not drift: the catalog is what
    // Phase 2 reads, the function is what Phase 1 writes, and a disagreement
    // would create a group nothing ever looks for.
    let catalog = domo_bootstrap::catalog::parse(include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../authz/catalog.toml"
    )))
    .expect("the shipped catalog must be valid");

    for kind in [
        Kind::Portfolio,
        Kind::Site,
        Kind::SiteCommon,
        Kind::BuildingCommon,
        Kind::Apartment,
        Kind::Building,
        Kind::Device,
    ] {
        let from_code: Vec<String> = naming::structural_groups_for(kind)
            .into_iter()
            .map(str::to_owned)
            .collect();
        let from_catalog = catalog.roles_for(naming::resource_type(kind));
        assert_eq!(
            from_code, from_catalog,
            "naming.rs and authz/catalog.toml disagree for {kind:?}"
        );
    }
}
