#!/usr/bin/env bash
#
# Offline PKI for the AXIAM Domo Demo.
#
# Generates the ONE organization root (once, ever) and re-issues every server
# leaf plus the single root-signed client leaf on each run.
#
#   .secrets/pki/root.key           RSA-4096, PKCS#8, mode 0600 — never rotated
#   .secrets/pki/root.pem           the single trust anchor, imported by AXIAM (BYOK)
#   .secrets/pki/<listener>.{pem,key}  ECDSA P-256 leaves from deploy/pki/listeners.conf
#
# D-10: the root is generated once and is NOT regenerated by `just demo-reset`.
# Rotating it invalidates every machine that has already trusted it; that is
# `just pki-rotate-root`'s job, not this script's.
#
# PKCS#8 matters: AXIAM's `rcgen::KeyPair::from_pem` accepts PKCS#8 and rejects
# the PKCS#1 form (P-5). `openssl genpkey` emits PKCS#8; `openssl genrsa` does not.
#
# Usage: scripts/gen-pki.sh
# Env:   DOMO_HOST (default: domo.local), DOMO_LAN_IP (default: 127.0.0.1)

set -euo pipefail

umask 077

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

PKI_DIR=".secrets/pki"
STATE_DIR=".secrets/state"
LISTENERS="deploy/pki/listeners.conf"
ROOT_GUARD="${STATE_DIR}/pki-root.done"

DOMO_HOST="${DOMO_HOST:-domo.local}"
DOMO_LAN_IP="${DOMO_LAN_IP:-127.0.0.1}"

MIN_FREE_GB=8

say()  { printf '  %s\n' "$*"; }
fail() { printf '✗ %s\n' "$*" >&2; exit 1; }

# --- disk hygiene gate (project CLAUDE.md: never build under 8 GB free) -------
check_disk() {
    local mp avail
    for mp in /home /; do
        [ -d "$mp" ] || continue
        avail=$(df -BG --output=avail "$mp" 2>/dev/null | tail -1 | tr -dc '0-9')
        [ -n "$avail" ] || continue
        if [ "$avail" -lt "$MIN_FREE_GB" ]; then
            fail "only ${avail}G free on ${mp}; need ${MIN_FREE_GB}G. Reclaim space before issuing certificates."
        fi
    done
}

check_disk

[ -f "$LISTENERS" ] || fail "missing ${LISTENERS}"
command -v openssl >/dev/null 2>&1 || fail "openssl not on PATH"

mkdir -p "$PKI_DIR" "$STATE_DIR"

# --- 1. the organization root, once and only once ----------------------------
if [ -f "$ROOT_GUARD" ] && [ -f "${PKI_DIR}/root.key" ] && [ -f "${PKI_DIR}/root.pem" ]; then
    say "root CA already present — reusing (D-10: never rotated by reset)"
else
    if [ -f "${PKI_DIR}/root.key" ] || [ -f "${PKI_DIR}/root.pem" ]; then
        fail "half-generated root in ${PKI_DIR} (guard ${ROOT_GUARD} absent). Refusing to overwrite key material; remove it deliberately or restore the guard."
    fi
    say "generating organization root (RSA-4096, PKCS#8, 10y)"
    openssl genpkey -quiet -algorithm RSA -pkeyopt rsa_keygen_bits:4096 \
        -out "${PKI_DIR}/root.key"
    chmod 600 "${PKI_DIR}/root.key"

    # No pathlen: AXIAM issues tenant signing CAs beneath this root, and a
    # pathlen:0 would forbid exactly that intermediate tier.
    openssl req -x509 -new -key "${PKI_DIR}/root.key" -sha256 -days 3650 \
        -subj "/CN=Domo Demo Root CA/O=AXIAM Domo Demo" \
        -addext "basicConstraints=critical,CA:TRUE" \
        -addext "keyUsage=critical,keyCertSign,cRLSign" \
        -addext "subjectKeyIdentifier=hash" \
        -out "${PKI_DIR}/root.pem"
    chmod 644 "${PKI_DIR}/root.pem"
    : > "$ROOT_GUARD"
    say "root fingerprint: $(openssl x509 -noout -fingerprint -sha256 -in "${PKI_DIR}/root.pem" | cut -d= -f2)"
fi

# --- 2. leaves, re-issued every run ------------------------------------------
issue_leaf() {
    local name="$1" kind="$2" sans="$3"
    local key="${PKI_DIR}/${name}.key"
    local crt="${PKI_DIR}/${name}.pem"
    local csr ext eku

    case "$kind" in
        server)
            [ -n "$sans" ] || fail "no SAN entries for ${name}"
            eku="serverAuth"
            ;;
        client)
            [ -z "$sans" ] || fail "client leaf ${name} must not carry SAN entries"
            eku="clientAuth"
            ;;
        *) fail "unknown kind '${kind}' for ${name} in ${LISTENERS}" ;;
    esac

    csr="$(mktemp)"; ext="$(mktemp)"
    trap 'rm -f "$csr" "$ext"' RETURN

    openssl genpkey -quiet -algorithm EC -pkeyopt ec_paramgen_curve:P-256 -out "$key"
    chmod 600 "$key"
    openssl req -new -key "$key" -subj "/CN=${name}/O=AXIAM Domo Demo" -out "$csr"

    {
        echo "basicConstraints=CA:FALSE"
        echo "keyUsage=critical,digitalSignature"
        echo "extendedKeyUsage=${eku}"
        echo "subjectKeyIdentifier=hash"
        echo "authorityKeyIdentifier=keyid:always"
        [ -n "$sans" ] && echo "subjectAltName=${sans}"
    } > "$ext"

    # 397 days is the CA/Browser Forum maximum for a server certificate and is
    # what the acceptance gate asserts (notAfter - notBefore <= 397d).
    openssl x509 -req -in "$csr" \
        -CA "${PKI_DIR}/root.pem" -CAkey "${PKI_DIR}/root.key" -CAcreateserial \
        -days 397 -sha256 -copy_extensions none -extfile "$ext" \
        -out "$crt" 2>/dev/null
    chmod 644 "$crt"
    say "issued ${name} (${eku})"
}

while IFS='|' read -r name kind sans; do
    # Skip comments and blank lines.
    case "${name# }" in ''|\#*) continue ;; esac
    name="$(echo "$name" | tr -d '[:space:]')"
    kind="$(echo "$kind" | tr -d '[:space:]')"
    sans="$(echo "${sans:-}" | tr -d '[:space:]')"
    # Expand the two operator-supplied placeholders.
    sans="${sans//\$\{DOMO_HOST\}/$DOMO_HOST}"
    sans="${sans//\$\{DOMO_LAN_IP\}/$DOMO_LAN_IP}"
    # De-duplicate: DOMO_LAN_IP may resolve to a value the row already lists
    # (notably the 127.0.0.1 default), and openssl would emit the SAN twice.
    sans="$(echo "$sans" | tr ',' '\n' | awk 'NF && !seen[$0]++' | paste -sd, -)"
    [ -n "$name" ] || continue
    issue_leaf "$name" "$kind" "$sans"
done < "$LISTENERS"

chmod 600 "${PKI_DIR}"/*.key
say "PKI ready in ${PKI_DIR} (host=${DOMO_HOST} lan_ip=${DOMO_LAN_IP})"
